services:
  db_pachamama:
    image: docker.io/library/postgres:16
    container_name: pachamama_database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_pachamama:/var/lib/postgresql/data

volumes:
  db_pachamama: